version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: local-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: alibin
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
